## example hit const ApiUrl = "https://api.deepseek.com/v1/chat/completions"
POST https://api.deepseek.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer 

{
  "model": "deepseek-chat",
  "messages": [
    {
      "role": "user",
      "content": "Current date is: 2025-05-26\n\nAnalyze the following transaction description:\nsaya beli motor kemaren insya Allah senilai 3jt500k\n\nInterpret any relative time expressions based on the current date above.\n\nExtract and reply in JSON format only:\n{\n\t\"type\": \"INCOME|EXPENSE\",\n\t\"amount\": number,\n\t\"category\": string,\n\t\"date\": \"YYYY-MM-DD\" or null\n}\n\nUse one of these categories:\n- Makanan & Minuman\n- Transportasi\n- Belanja\n- Tagihan & Utilitas\n- Pendidikan\n- Kesehatan\n- Hiburan\n- Donasi & Sosial\n- Perawatan Diri\n- Cicilan / Kredit\n- Pajak & Retribusi\n- Investasi & Tabungan\n- Biaya Rumah Tangga\n- Biaya Anak\n- Hewan Peliharaan\n- Lain-lain\n- Gaji / Pendapatan Tetap\n- Bisnis / Dagang\n- Investasi\n- Hadiah / Hibah\n- Penjualan Aset\n- Pengembalian Uang\n- Lain-lain\n\nOutput must be in Bahasa Indonesia."
    }
  ]
}

###
GET https://duite-bot.brogrammer.id/health
Content-Type: application/json

### Chat GPT-4.1 nano
POST https://api.openai.com/v1/responses
Content-Type: application/json
Authorization: Bearer 

{
  "model": "gpt-4.1-nano",
  "input": [
    {
      "role": "user",
      "content": [
        {
          "type": "input_text",
          "text": "Current date is: 2025-05-26\n\nAnalyze the following transaction description:\nsaya motor insya allah besok senilai 3jt500rb\n\nInterpret any relative time expressions based on the current date above.\n\nExtract and reply in JSON format only:\n{\n\t\"type\": \"INCOME|EXPENSE\",\n\t\"amount\": number,\n\t\"category\": string,\n\t\"date\": \"YYYY-MM-DD\" or null\n}\n\nUse one of these categories:\n- Makanan & Minuman\n- Transportasi\n- Belanja\n- Tagihan & Utilitas\n- Pendidikan\n- Kesehatan\n- Hiburan\n- Donasi & Sosial\n- Perawatan Diri\n- Cicilan / Kredit\n- Pajak & Retribusi\n- Investasi & Tabungan\n- Biaya Rumah Tangga\n- Biaya Anak\n- Hewan Peliharaan\n- Lain-lain\n- Gaji / Pendapatan Tetap\n- Bisnis / Dagang\n- Investasi\n- Hadiah / Hibah\n- Penjualan Aset\n- Pengembalian Uang\n- Lain-lain\n\nOutput must be in Bahasa Indonesia."
        }
      ]
    }
  ],
  "text": {
    "format": {
      "type": "json_object"
    }
  },
  "reasoning": {},
  "tools": [],
  "temperature": 1,
  "max_output_tokens": 2048,
  "top_p": 1,
  "store": true
}

###
DELETE http://localhost:8080/users/1131652151/transactions/43
Content-Type: application/json

###
POST http://localhost:9000/users/6282117088123/transactions/ai-classify
Content-Type: application/json

{
  "prompt": "beli jajan cilok 101k"
}

###
POST http://localhost:9000/users/register
Content-Type: application/json

{
  "chat_id": 12345678,
  "name": "IkhsanJH"
}

###
GET http://localhost:9000/users/62821170881423/transactions/daily
Content-Type: application/json


