services:
  bot-tele:
    build:
      context: ./bot-tele
    container_name: bot-tele
    restart: unless-stopped
    environment:
      APP_ENV: production
    depends_on:
      - db
      - redis
    volumes:
      - ./bot-tele:/app
      - ./.env:/app/.env
    working_dir: /app
    command: ./bot
    networks:
      - internal

  bot-wa:
    build:
      context: ./bot-wa
    container_name: bot-wa
    restart: unless-stopped
    environment:
      APP_ENV: production
    depends_on:
      - db
      - redis
    volumes:
      - ./bot-wa:/app
      - ./.env:/app/.env
    working_dir: /app
    command: node index.js
    networks:
      - internal

  core-api:
    build:
      context: ./core-api
    container_name: core-api
    restart: unless-stopped
    environment:
      APP_ENV: production
    depends_on:
      - db
      - redis
    volumes:
      - ./core-api:/app
      - ./.env:/app/.env
    working_dir: /app
    command: ./start-api
    networks:
      - internal

  db:
    image: postgres:15
    container_name: duite-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7
    container_name: duite-redis
    restart: unless-stopped
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
  