services:
  bot-tele:
    container_name: bot-tele
    restart: unless-stopped
    volumes:
      - ./bot-tele:/app
      - ./.env:/app/.env
    working_dir: /app
    command: ./bot
    depends_on:
      - db
      - redis
    networks:
      - internal

  bot-wa:
    container_name: bot-wa
    restart: unless-stopped
    volumes:
      - ./bot-wa:/app
      - ./.env:/app/.env
    working_dir: /app
    command: node index.js
    depends_on:
      - db
      - redis
    networks:
      - internal

  core-api:
    container_name: core-api
    restart: unless-stopped
    environment:
      APP_ENV: production
    depends_on:
      - db
      - redis
    volumes:
      - ./core-api:/app
      - ./.env:/app/.env
    working_dir: /app
    command: ./core-api
    networks:
      - internal
  
  gateway:
    container_name: gateway
    restart: unless-stopped
    environment:
      APP_ENV: production
    # ports:
    #   - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - db
      - redis
    volumes:
      - ./gateway:/app
      - ./.env:/app/.env
    working_dir: /app
    command: ./gateway
    networks:
      - internal

  db:
    image: postgres:15
    container_name: duite-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7
    container_name: duite-redis
    restart: unless-stopped
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
